
import { EnergyLevel, Gender, PetProfile, Size, SocialPost, Species } from "./types";

export const TRANSLATIONS = {
  en: {
    nav: {
      feed: 'Feed',
      discovery: 'Discovery',
      beeline: 'Likes',
      matches: 'Matches',
      profile: 'Profile',
    },
    discovery: {
      title: 'Discover',
      allCaughtUp: 'All caught up!',
      checkLater: 'Check back later for more pals.',
      refresh: 'Refresh Radar',
      like: 'LIKE',
      nope: 'NOPE',
      report: 'Report & Block',
      reportSub: 'Your safety is our priority.',
      about: 'About',
      myHuman: 'Owner',
      distance: 'km away',
      vibeCheck: 'Vibe Check',
      morePhotos: 'More Photos',
      respondsIn: 'Responds within an hour',
      filters: 'Filters',
      premiumFeature: 'Premium Feature',
      unlockFilters: 'Upgrade to Top Dog to unlock advanced filters!',
    },
    beeline: {
      title: 'Who Liked You',
      upgradeTitle: 'See Who Likes You',
      upgradeSub: 'Upgrade to Top Dog Premium to reveal these profiles and match instantly.',
      waiting: 'PetPals waiting',
      unlock: 'Unlock All - 99K',
    },
    premium: {
      title: 'Top Dog Premium',
      popular: 'MOST POPULAR',
      bestValue: 'BEST VALUE',
      month: 'month',
      save: 'SAVE',
      benefits: {
        beeline: 'See who liked you',
        filters: 'Advanced Filters',
        undo: 'Unlimited Rewinds',
        badge: 'Top Dog Badge',
      },
      cta: 'Upgrade Now',
      restore: 'Restore Purchase',
    },
    profile: {
      editPhoto: 'Change Photo',
      name: 'Name',
      age: 'Age',
      aboutMe: 'About Me',
      placeholderBio: 'Write something pawesome...',
      interests: 'Interests & Energy',
      compatibility: 'Compatibility',
      add: 'Add',
      save: 'Save Changes',
      create: 'Create Profile',
      saving: 'Saving...',
      saved: 'Saved!',
      successTitle: 'Profile Saved Successfully',
      successMsg: 'Your changes are live and ready to impress!',
      healthRecords: 'Health Records',
      myPets: 'My Pets',
      newPet: 'New Pet',
    },
    health: {
      title: 'Health Records',
      vaccinations: 'Vaccinations',
      vetVisits: 'Vet Visits',
      medications: 'Medications',
      add: 'Add Record',
      name: 'Name',
      date: 'Date',
      nextDue: 'Next Due',
      clinic: 'Clinic',
      reason: 'Reason',
      dosage: 'Dosage',
      frequency: 'Frequency',
      notes: 'Notes',
      empty: 'No records yet.',
      callVet: 'Call Vet',
      emailVet: 'Email Vet',
      phone: 'Phone',
      email: 'Email',
    },
    settings: {
      title: 'Settings & Privacy',
      account: 'Account',
      privacy: 'Privacy',
      notifications: 'Notifications',
      general: 'General',
      language: 'Language',
      selectLanguage: 'Select Language',
      logout: 'Log Out',
      profileInfo: 'Profile Information',
      changeEmail: 'Change Email',
      changePassword: 'Change Password',
      deleteAccount: 'Delete Account',
      pushNotifs: 'Push Notifications',
      emailNotifs: 'Email Notifications',
      terms: 'Terms of Service',
      help: 'Help & Support',
    },
    matches: {
      connect: 'Connect',
      newMatches: 'New Matches',
      messages: 'Messages',
      noMatches: 'No new matches. Keep swiping!',
      expiring: 'left',
      yourTurn: 'YOUR TURN',
      matchTitle: "It's a Pawsome Match!",
      matchSub: 'You and {name} have liked each other.',
      sendMessage: 'Send a Message',
      keepSwiping: 'Keep Swiping',
    },
    feed: {
      title: 'PetPals Feed',
    }
  },
  vi: {
    nav: {
      feed: 'Bảng tin',
      discovery: 'Khám phá',
      beeline: 'Đã thích',
      matches: 'Tương hợp',
      profile: 'Hồ sơ',
    },
    discovery: {
      title: 'Khám phá',
      allCaughtUp: 'Đã hết hồ sơ!',
      checkLater: 'Hãy quay lại sau để xem thêm.',
      refresh: 'Làm mới',
      like: 'THÍCH',
      nope: 'KHÔNG',
      report: 'Báo cáo & Chặn',
      reportSub: 'An toàn của bạn là ưu tiên hàng đầu.',
      about: 'Giới thiệu',
      myHuman: 'Chủ nhân',
      distance: 'km cách đây',
      vibeCheck: 'Tính cách / Sở thích',
      morePhotos: 'Ảnh khác',
      respondsIn: 'Phản hồi trong 1 giờ',
      filters: 'Bộ lọc',
      premiumFeature: 'Tính năng Cao cấp',
      unlockFilters: 'Nâng cấp lên Top Dog để mở khóa bộ lọc nâng cao!',
    },
    beeline: {
      title: 'Ai đã thích bạn',
      upgradeTitle: 'Xem ai thích bạn',
      upgradeSub: 'Nâng cấp Top Dog Premium để xem hồ sơ và tương hợp ngay lập tức.',
      waiting: 'PetPals đang chờ',
      unlock: 'Mở khóa - 99K',
    },
    premium: {
      title: 'Top Dog Premium',
      popular: 'PHỔ BIẾN NHẤT',
      bestValue: 'GIÁ TRỊ NHẤT',
      month: 'tháng',
      save: 'TIẾT KIỆM',
      benefits: {
        beeline: 'Xem ai đã thích bạn',
        filters: 'Bộ lọc nâng cao',
        undo: 'Quay lại không giới hạn',
        badge: 'Huy hiệu Top Dog',
      },
      cta: 'Nâng cấp ngay',
      restore: 'Khôi phục giao dịch',
    },
    profile: {
      editPhoto: 'Đổi ảnh',
      name: 'Tên',
      age: 'Tuổi',
      aboutMe: 'Giới thiệu',
      placeholderBio: 'Viết gì đó thật ngầu...',
      interests: 'Sở thích & Năng lượng',
      compatibility: 'Tương thích',
      add: 'Thêm',
      save: 'Lưu thay đổi',
      create: 'Tạo hồ sơ',
      saving: 'Đang lưu...',
      saved: 'Đã lưu!',
      successTitle: 'Lưu hồ sơ thành công',
      successMsg: 'Thay đổi của bạn đã được cập nhật!',
      healthRecords: 'Sổ sức khỏe',
      myPets: 'Thú cưng của tôi',
      newPet: 'Thêm mới',
    },
    health: {
      title: 'Sổ sức khỏe',
      vaccinations: 'Tiêm phòng',
      vetVisits: 'Khám thú y',
      medications: 'Thuốc',
      add: 'Thêm',
      name: 'Tên',
      date: 'Ngày',
      nextDue: 'Hết hạn / Tiếp theo',
      clinic: 'Phòng khám',
      reason: 'Lý do',
      dosage: 'Liều lượng',
      frequency: 'Tần suất',
      notes: 'Ghi chú',
      empty: 'Chưa có dữ liệu.',
      callVet: 'Gọi bác sĩ',
      emailVet: 'Gửi Email',
      phone: 'Số điện thoại',
      email: 'Email',
    },
    settings: {
      title: 'Cài đặt & Quyền riêng tư',
      account: 'Tài khoản',
      privacy: 'Quyền riêng tư',
      notifications: 'Thông báo',
      general: 'Chung',
      language: 'Ngôn ngữ',
      selectLanguage: 'Chọn ngôn ngữ',
      logout: 'Đăng xuất',
      profileInfo: 'Thông tin hồ sơ',
      changeEmail: 'Đổi Email',
      changePassword: 'Đổi mật khẩu',
      deleteAccount: 'Xóa tài khoản',
      pushNotifs: 'Thông báo đẩy',
      emailNotifs: 'Thông báo Email',
      terms: 'Điều khoản dịch vụ',
      help: 'Trợ giúp & Hỗ trợ',
    },
    matches: {
      connect: 'Kết nối',
      newMatches: 'Tương hợp mới',
      messages: 'Tin nhắn',
      noMatches: 'Chưa có tương hợp mới. Hãy tiếp tục quẹt!',
      expiring: 'còn lại',
      yourTurn: 'LƯỢT BẠN',
      matchTitle: "Tương hợp hoàn hảo!",
      matchSub: 'Bạn và {name} đã thích nhau.',
      sendMessage: 'Gửi tin nhắn',
      keepSwiping: 'Tiếp tục quẹt',
    },
    feed: {
      title: 'Bảng tin PetPals',
    }
  }
};

export const MOCK_PETS: PetProfile[] = [
  {
    id: '1',
    name: 'Vàng',
    species: Species.DOG,
    breed: 'Golden Retriever',
    age: 2,
    gender: Gender.MALE,
    isNeutered: true,
    images: [
      'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=800&q=80', 
      'https://images.unsplash.com/photo-1611003228941-98852ba62227?auto=format&fit=crop&w=800&q=80'
    ],
    energyLevel: EnergyLevel.HIGH,
    size: Size.LARGE,
    vibes: ['Squeaky Toys', 'Belly Rubs', 'Water Lover'],
    compatibility: ['Good with Dogs', 'Loves People'],
    bio: 'Thích gặm gậy và chạy nhảy. Cần tìm bạn chạy bộ cùng!',
    distance: 3.5,
    ownerName: 'Hùng',
    isVerified: true,
  },
  {
    id: '2',
    name: 'Miu',
    species: Species.CAT,
    breed: 'Scottish Fold',
    age: 4,
    gender: Gender.FEMALE,
    isNeutered: true,
    images: [
      'https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1495360019602-e05980db76af?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1588943211346-0908a1fb0b01?q=80&w=435&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'
    ],
    energyLevel: EnergyLevel.LOW,
    size: Size.SMALL,
    vibes: ['Naps', 'Laser Pointer', 'Judgemental Stares'],
    compatibility: ['Cat Friendly', 'Quiet Home'],
    bio: 'Tôi là bà chủ nhà này. Quẹt phải nếu bạn có pate ngon.',
    distance: 1.2,
    ownerName: 'Minh',
    isVerified: true,
  },
  {
    id: '3',
    name: 'Bơ',
    species: Species.DOG,
    breed: 'French Bulldog',
    age: 3,
    gender: Gender.MALE,
    isNeutered: true,
    images: [
      'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1583511655826-05700d52f4d9?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MzV8fGRvZ3xlbnwwfHwwfHx8MA%3D%3D'
    ],
    energyLevel: EnergyLevel.MEDIUM,
    size: Size.SMALL,
    vibes: ['Snoring', 'Cuddles', 'Foodie'],
    compatibility: ['Kid-Friendly', 'Apartment Dog'],
    bio: 'Thân hình nhỏ nhưng tính cách lớn. Ngáy to hơn bố bạn.',
    distance: 8.0,
    ownerName: 'Lan',
  },
  {
    id: '4',
    name: 'Lu',
    species: Species.DOG,
    breed: 'Husky Mix',
    age: 5,
    gender: Gender.FEMALE,
    isNeutered: true,
    images: [
      'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1605568427561-40dd23d2acca?auto=format&fit=crop&w=800&q=80'
    ],
    energyLevel: EnergyLevel.HIGH,
    size: Size.LARGE,
    vibes: ['Singing', 'Hiking', 'Escape Artist'],
    compatibility: ['Needs Backyard', 'High Energy'],
    bio: 'Thích "hát" vào lúc 3 giờ sáng. Đi phượt không?',
    distance: 12.5,
    ownerName: 'Tâm',
    isVerified: true,
  },
  {
    id: '5',
    name: 'Milu',
    species: Species.DOG,
    breed: 'Beagle',
    age: 1,
    gender: Gender.MALE,
    isNeutered: false,
    images: [
      'https://images.unsplash.com/photo-1537151625747-768eb6cf92b2?auto=format&fit=crop&w=800&q=80',
      'https://plus.unsplash.com/premium_photo-1666777247416-ee7a95235559?q=80&w=387&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'
    ],
    energyLevel: EnergyLevel.HIGH,
    size: Size.MEDIUM,
    vibes: ['Sniffing Everything', 'Howling', 'Treats'],
    compatibility: ['Dog Friendly', 'Patient Owners'],
    bio: 'Cái gì thơm là đuổi theo. Đơn giản vậy thôi.',
    distance: 5.2,
    ownerName: 'Dũng',
  },
  {
    id: '6',
    name: 'Mun',
    species: Species.CAT,
    breed: 'Bombay',
    age: 2,
    gender: Gender.MALE,
    isNeutered: true,
    images: [
      'https://images.unsplash.com/photo-1513245543132-31f507417b26?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1503256207526-0d5d80fa2f47?q=80&w=386&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'
    ],
    energyLevel: EnergyLevel.MEDIUM,
    size: Size.SMALL,
    vibes: ['Night Prowler', 'Purring Machine', 'Box Lover'],
    compatibility: ['No Dogs', 'Indoor Only'],
    bio: 'Hoàng tử bóng đêm. Cho xin ít cá ngừ đi.',
    distance: 2.8,
    ownerName: 'Vy',
    isVerified: true,
  }
];

// Profiles for Beeline (Who Liked Me)
export const MOCK_LIKED_BY: PetProfile[] = [
  {
    id: 'l1',
    name: 'Rocky',
    species: Species.DOG,
    breed: 'Boxer',
    age: 4,
    gender: Gender.MALE,
    isNeutered: true,
    images: ['https://images.unsplash.com/photo-1548658166-136d9f6a7ea3?auto=format&fit=crop&w=800&q=80'],
    energyLevel: EnergyLevel.HIGH,
    size: Size.LARGE,
    vibes: ['Playful', 'Drools'],
    compatibility: ['Dogs'],
    bio: 'Looking for a playmate!',
    distance: 5,
    ownerName: 'Mike',
    isVerified: true
  },
  {
    id: 'l2',
    name: 'Luna',
    species: Species.DOG,
    breed: 'Samoyed',
    age: 2,
    gender: Gender.FEMALE,
    isNeutered: true,
    images: ['https://images.unsplash.com/photo-1529429617124-95b109e86bb8?auto=format&fit=crop&w=800&q=80'],
    energyLevel: EnergyLevel.MEDIUM,
    size: Size.MEDIUM,
    vibes: ['Fluffy', 'Gentle'],
    compatibility: ['Kids'],
    bio: 'I am a cloud with legs.',
    distance: 12,
    ownerName: 'Sarah',
  },
  {
    id: 'l3',
    name: 'Simba',
    species: Species.CAT,
    breed: 'Maine Coon',
    age: 5,
    gender: Gender.MALE,
    isNeutered: true,
    images: ['https://images.unsplash.com/photo-1533738363-b7f9aef128ce?auto=format&fit=crop&w=800&q=80'],
    energyLevel: EnergyLevel.LOW,
    size: Size.LARGE,
    vibes: ['Majestic', 'Lazy'],
    compatibility: ['Cats'],
    bio: 'King of the jungle (living room).',
    distance: 1,
    ownerName: 'Tom',
    isVerified: true
  },
  {
    id: 'l4',
    name: 'Coco',
    species: Species.DOG,
    breed: 'Poodle',
    age: 3,
    gender: Gender.FEMALE,
    isNeutered: true,
    images: ['https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=800&q=80'],
    energyLevel: EnergyLevel.MEDIUM,
    size: Size.SMALL,
    vibes: ['Fashion', 'Smart'],
    compatibility: ['Anyone'],
    bio: 'Beauty with brains.',
    distance: 7,
    ownerName: 'Emily',
  }
];

export const MOCK_POSTS: SocialPost[] = [
  {
    id: 'p1',
    authorId: 'user_1',
    authorName: 'Vàng & Hùng',
    isVerified: true,
    authorImage: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=150&q=80',
    content: 'Ngày đầu tiên đi biển! Cát dính khắp nơi nhưng vui lắm. 🏖️🐾',
    image: 'https://images.unsplash.com/photo-1519098901909-b1553a1190af?auto=format&fit=crop&w=800&q=80',
    likes: 124,
    comments: 12,
    timestamp: '2h ago',
  },
  {
    id: 'p2',
    authorId: 'user_2',
    authorName: 'Miu Hoàng Gia',
    isVerified: true,
    authorImage: 'https://images.unsplash.com/photo-1529778873920-4da4926a7071?auto=format&fit=crop&w=150&q=80',
    content: 'Vừa tìm được cái hộp mới. Tạm chấp nhận.',
    image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=800&q=80',
    likes: 89,
    comments: 5,
    timestamp: '4h ago',
  },
  {
    id: 'p3',
    authorId: 'user_3',
    authorName: 'Lu Ngáo',
    authorImage: 'https://images.unsplash.com/photo-1591769225440-811ad7d6eca6?auto=format&fit=crop&w=150&q=80',
    content: 'Gặp bạn mới ở công viên! Chạy mệt nghỉ.',
    image: 'https://images.unsplash.com/photo-1568572933382-74d440642117?auto=format&fit=crop&w=800&q=80',
    likes: 256,
    comments: 34,
    timestamp: '6h ago',
  },
  {
    id: 'p4',
    authorId: 'user_4',
    authorName: 'Mèo Nala',
    authorImage: 'https://images.unsplash.com/photo-1519052537078-e6302a4968d4?auto=format&fit=crop&w=150&q=80',
    content: 'Vừa ngủ dậy. Chắc đi ngủ tiếp đây.',
    image: 'https://images.unsplash.com/photo-1513360371669-4adf3dd7dff8?auto=format&fit=crop&w=800&q=80',
    likes: 412,
    comments: 18,
    timestamp: '10h ago',
  }
];

// Current User Mock
export const CURRENT_USER_PET: PetProfile = {
  id: 'me',
  name: 'Kiki',
  species: Species.DOG,
  breed: 'Corgi',
  age: 2,
  gender: Gender.FEMALE,
  isNeutered: true,
  images: ['https://images.unsplash.com/photo-1612536053388-c39f49cb7460?auto=format&fit=crop&w=800&q=80'],
  energyLevel: EnergyLevel.MEDIUM,
  size: Size.SMALL,
  vibes: ['Ball is Life', 'Cuddling', 'High Energy'],
  compatibility: ['Good with Dogs', 'Kid-Friendly', 'Loves People'],
  bio: 'Kiki là cục bông vui vẻ, thích đi dạo và chơi ném bóng. Rất thích được ôm và gãi bụng.',
  distance: 0,
  ownerName: 'Bạn',
};

export const PLACEHOLDER_IMAGE = 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=800&q=80';
export const PLACEHOLDER_AVATAR = 'https://ui-avatars.com/api/?name=User&background=random';
